from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import re


# =========================
# 🔹 CLEAN HTML TAGS
# =========================
def clean_html(text):
    text = re.sub(r'<span.*?>', '', text)
    text = re.sub(r'</span>', '', text)
    text = re.sub(r'<.*?>', '', text)
    return text


# =========================
# 🔹 SIMPLE AI SUMMARY
# =========================
def generate_simple_summary(clause):
    clause = clause.lower()
    summary = []

    if "terminate" in clause:
        summary.append("Explains termination conditions")
    if "penalty" in clause:
        summary.append("Includes financial penalty")
    if "liability" in clause:
        summary.append("Mentions liability risks")
    if "confidential" in clause:
        summary.append("Protects company confidential data")
    if "salary" in clause:
        summary.append("Defines salary/payment terms")
    if "notice" in clause:
        summary.append("Includes notice period rules")

    if not summary:
        return "General contract condition."
    return " | ".join(summary)


# =========================
# 🔹 REASON GENERATOR
# =========================
def generate_reason(clause, risk):
    clause = clause.lower()
    reasons = []

    if "terminate" in clause:
        reasons.append("Termination clause present")
    if "penalty" in clause:
        reasons.append("Financial penalty involved")
    if "liability" in clause:
        reasons.append("Liability risk noted")
    if "without notice" in clause:
        reasons.append("No notice period")

    if not reasons:
        reasons.append("General contract condition")
    return reasons


# =========================
# 🔹 PDF GENERATION
# =========================
def generate_pdf(results, filename="report.pdf"):
    doc = SimpleDocTemplate(filename, rightMargin=40, leftMargin=40, topMargin=50, bottomMargin=50)
    styles = getSampleStyleSheet()

    # Custom Premium Styles
    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=HexColor("#1e293b"),
        alignment=TA_CENTER,
        spaceAfter=30
    )
    
    clause_heading = ParagraphStyle(
        'ClauseHeading',
        parent=styles['Heading3'],
        fontSize=14,
        textColor=HexColor("#334155"),
        spaceAfter=10,
        spaceBefore=15
    )

    clause_body = ParagraphStyle(
        'ClauseBody',
        parent=styles['Normal'],
        fontSize=11,
        textColor=HexColor("#475569"),
        leading=16,
        spaceAfter=15
    )
    
    meta_style = ParagraphStyle(
        'MetaStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=HexColor("#64748b"),
        leading=14
    )

    content = []

    # 📌 Title
    content.append(Paragraph("<b>Contract Risk Analysis Report</b>", title_style))
    content.append(Paragraph("Autogenerated by AI Analyzer", meta_style))
    content.append(Spacer(1, 10))
    content.append(HRFlowable(width="100%", thickness=1, color=HexColor("#cbd5e1")))
    content.append(Spacer(1, 30))

    # 🔁 Loop through clauses
    for i, item in enumerate(results, 1):
        clause = clean_html(item["clause"])
        risk = item["risk"]
        score = item["score"]

        # 🧠 AI Summary & Reasons
        summary = generate_simple_summary(clause)
        reasons = generate_reason(clause, risk)

        # 🎨 Risk styling
        if risk == "High":
            risk_color = "#ef4444"
            risk_icon = "🔴"
        elif risk == "Medium":
            risk_color = "#f59e0b"
            risk_icon = "🟡"
        else:
            risk_color = "#10b981"
            risk_icon = "🟢"

        # 📄 Block Constructor
        content.append(Paragraph(f"<b>{i}. Analyzed Clause</b>", clause_heading))
        content.append(Paragraph(f'"{clause}"', clause_body))

        meta_html = f"""
        <b>Risk Level:</b> <font color="{risk_color}">{risk_icon} {risk.upper()}</font><br/>
        <b>Risk Score:</b> {score}<br/><br/>
        <b>🧠 Simple Summary:</b> {summary}<br/>
        <b>🔎 Key Points:</b>
        """
        content.append(Paragraph(meta_html, meta_style))

        # ➕ Add bullet reasons
        for r in reasons:
            content.append(Paragraph(f"• {r}", meta_style))

        content.append(Spacer(1, 25))
        content.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e2e8f0")))
        content.append(Spacer(1, 20))

    # 📥 Build PDF
    doc.build(content)
    return filename
